### ISSUE TITLE
allow internal trees in one level

### ISSUE THREAD

**Issue by florianschanda** [bmw-software-engineering/lobster#18]
Requirement A that inside one level is decomposed into B and C, would be OK if B and C are themselves OK.

Policy example:
```
requirements "Requirements" {
   source: "potato.lobster";
}

implementation "Code" {
   source: "code.lobster";
   trace to: "Requirements" with internal_links;
}

activity "Test" {
   source: "test.lobster";
   trace to: "Requirements";
}
```

OR perhaps allow self-references:
```
requirements "Requirements" {
   source: "potato.lobster";
   requires: "Code" or self_reference;
   requires: "Test";
}

implementation "Code" {
   source: "code.lobster";
   trace to: "Requirements"
}

activity "Test" {
   source: "test.lobster";
   trace to: "Requirements";
}
```

Would allow for example:
```
      R1
     / \
    R2  R3
    |   |
    C2  C3
```
As long as all requirements are individually tested.

Side-note: We now need to worry about cycles, i.e. `R1 -> R2, R2 -> R1` and should make sure that these do _not_ count.

This check only needs to be done for levels that allow self_references.

**Comment by phiwuu** [comment]
If `R1` is a real requirement, and if it is properly broken down into `R2` and `R3`, then nevertheless `R1` must be tested. This holds regardless of the test coverage of `R2` and `R3`. I will close this issue, but we can reopen it as soon as users claim it is a real use case for them.
