### ISSUE TITLE
lobster-python duplicates tests if using unittest

### ISSUE THREAD

**Issue by phiwuu** [bmw-software-engineering/lobster#20]
If `lobster-python` runs over a Python project where `unittest` is used instead of `pytest`, then each test is also interpreted as a regular function.
This leads to the result that the final lobster report shows each unit test twice (as a function and as a test).

We need to check if this happens only for `unittest`, or also for `pytest`.

**Comment by florianschanda** [comment]
Are you using the `--activity` flag for lobster-python to get the tests?
And are you making sure that lobster-python is run twice, once for the code (making sure that the tests are not accidentally passed) and once with `--activity` for the tests?

So if you have a dir structure like this:
```
my_module
tests
```

Then you should run it like so:
```
$ lobster-python my_module --out=code.lobster
$ lobster-python --activity tests --out=test.lobster
```

**Comment by phiwuu** [comment]
I see. Then it was indeed my mistake. I ran `lobster-python` over the tests folder, too, without the `--activity' flag, and was expecting that it ignores the tests. I will update the readme file accordingly.
