### ISSUE TITLE
Vanilla Example

### ISSUE THREAD

**Issue by phiwuu** [bmw-software-engineering/lobster#27]
Please create a "vanilla example" that demonstrates how to do the following:

- extract one requirement from a TRLC file with `lobster-trlc`
- extract one function from a Python file with `lobster-python`
- extract one test from a Python file with `lobster-python --activity`
- extract one function from a C++ file with `lobster-cpp`
- extract one requirement from codebeamer with `lobster-codebeamer`

and put it all together in a tracing policy, and generate an HTML lobster report.

Please think about the best way to publish the vanilla example. Maybe it is a good idea to provide a zip file, so that it easy extremely easy to download it.

The goal is to train interested users quickly how to use lobster.

**Comment by christophkloeffel** [comment]
vanilla example will be maintained in https://github.com/bmw-software-engineering/lobster-demo

**Comment by DiFerMa** [comment]
Issue closed with:

lobster main repo: https://github.com/bmw-software-engineering/lobster/pull/127

lobster-demo: https://github.com/bmw-software-engineering/lobster-demo/pull/8
