### ISSUE TITLE
Extend C/C++ Support

### ISSUE THREAD

**Issue by TannazVhdBMWExt** [bmw-software-engineering/lobster#57]
# Introduction
Many users struggle to use [lobster-cpp](https://github.com/bmw-software-engineering/lobster/tree/main/packages/lobster-tool-cpp) and/or [lobster-gtest](https://github.com/bmw-software-engineering/lobster/tree/main/packages/lobster-tool-gtest).
There is a variety of reasons, but the two most-often mentioned arguments are these:

- Their existing tool chain uses a different compiler or architecture (e.g. like [TASKING](https://www.tasking.com/products)).
- Their existing tool chain does not use [GoogleTest](https://github.com/google/googletest).
- Their existing tool chain uses [GoogleTest](https://github.com/google/googletest), but in a deeply nested manner in a complex tool chain, and adding/modifying the parameter `gtest_output` to generate local output causes a headache.
- Their existing code uses a different notation to link source code to requirements, and updating to use `lobster-trace: ...` for references is too much effort:
  - Replacing comments in the code base is expensive, especially if the code must follow [ISO 26262](https://en.wikipedia.org/wiki/ISO_26262) or [IEC 61508](https://en.wikipedia.org/wiki/IEC_61508) quality criteria, as this will require a review by an independent human, or the tool to refactor the files must be qualified according to those norms.
  - Teaching hundreds of software developers to apply a new notation requires massive training effort, even if the training per individual is very short.

Hence we need to extend the support for C/C++. The following modifications are necessary compared to `lobster-gtest` and `lobster-cpp`:
1. The tool shall not need to call a C/C++ compiler or related tool.
2. The tool shall be able to extract links from functions to artifacts even if linking the C/C++ code fails.
3. The tool shall not be limited to extracting links to requirements. Instead, it shall support the extraction of arbitrary references. Examples are references to defect tickets or component tests.

It is okay if the tool requires supports only a limited set of C++ expressions, if they are well-documented. For example, macro expansion does not need to be supported.

# Proposal
I propose to implement a new tool called `lobster-coda` (CODA: Comment Observation and Data Accumulation).

Parsing the C/C++ is not performed. Instead, `lobster-coda` searches for keywords in comments (with the help of regular expressions). Any function below such a comment is interpreted as a C++ test case, and a lobster trace entry is extracted. Macros are not expanded. The expression after the comment is treated as a string, and the test case name is extracted by assuming the following string pattern: `^[A-Z]+\(([a-zA-Z0-9]+),[a-zA-Z0-9]+\)$`. The first and only group in this regex is the test case name.

## Code Snippets
The following code snippets are examples that `lobster-code` shall be able to parse.
```cpp
/*
 @defect Some_Defect_Ticket_ID
 @requirement Some_Requirement_ID
*/

TEST(SomeFixture, something)
{
    result = Execute();
    EXPECT_EQ(result, 42);
}

```
Expectation:
```json
{
  "data": [
    {
      "tag": "cpp something_test.cpp:SomeFixture:123",
      "location": {
        "kind": "file",
        "file": "..\\something_test.cpp",
        "line": 123,
        "column": null
      },
      "name": "something_test.cpp:SomeFixture:123",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req Some_Requirement_ID",
        "defect Some_Defect_Ticket_ID"
      ],
      "framework": "cpp_test",
      "kind": "Function",
      "status": null
    },
  ],
  "generator": "lobster_coda",
  "schema": "lobster-act-trace",
  "version": 3
}
```

The strings `requirement` and `defect` shall be configurable by the user, and the user shall be able to provide regex to identify them. The regex shall contain groups to identify the values to extract (`Some_Defect_Ticket_ID` in the above example). The user shall also be able to configure the kind to use for references (`req` in the case of `Some_Requirement_ID`, and `defect` in case of `Some_Defect_Ticket_ID`). Note that `defect` is not a supported kind as of September 2024. `lobster-coda` shall not care about this. We will have to refactor the hard-coded kinds `req`, `act` and `imp` sooner or later in `lobster-report`, and make them configurable. `lobster-coda` shall prepare for this scenario.

## Assumptions
The tool `lobster-coda` may assume the following:
- There is at most one function per line. Each function is terminated with at least one line break.
- The references are either provided as comments to the functions in the `*.cpp` file or the `*.h` file, but never in both.
- Comments always apply to the first non-comment expression below the comment.

**Comment by phiwuu** [comment]
In the end the chosen name was `lobster-cpptest`, not `lobster-coda`, as suggested in this issue.
