### ISSUE TITLE
Create `venv` for pylint workflow action in `ci.yml`

### ISSUE THREAD

**Issue by phiwuu** [bmw-software-engineering/lobster#83]
Create a virtual environment in the CI workflow to remove the usage of `pip --break-system-packages`, which has been introduced with https://github.com/bmw-software-engineering/lobster/pull/81.
See https://github.com/bmw-software-engineering/lobster/blob/7017e874171f7c671fad03b9e7918267885abbdc/.github/workflows/ci.yml#L21-L22

**Comment by christophkloeffel** [comment]
creating a virtual environment serves the purpose of isolation. I argue that the job in the workflow does not need to be isolated again since there is no other job that gets executed in this VM (GitHub runner).
